name: mcts_handcoded_d30_n30_b100_c100

builder:
  _target_: rl_research.agents.mcts.MCTSAgent

params:
  _target_: rl_research.agents.mcts.MCTSAgentParams
  num_states: null
  num_actions: null
  discount: 0.9
  num_simulations: 100
  max_depth: 30
  rollout_length: 10
  ucb_bonus: 100
  tree_policy_bonus: 100
  dynamics_model:
    _target_: rl_research.models.goright_expectation_model
    is_partially_obs: false

autofill:
  num_states: tabular_num_states
  num_actions: tabular_num_actions

policy: null
