name: mbie

builder:
  _target_: rl_research.agents.MBIEAgent

params:
  _target_: rl_research.agents.MBIEParams
  num_states: null
  num_actions: null
  discount: 0.95
  threshold: 0.01
  r_max: 10000.0
  epsilon_r_coeff: 0.3
  epsilon_t_coeff: 0.0
  exploration_coeff: 0.0
  m: null
  use_exploration_bonus: false

autofill:
  num_states: tabular_num_states
  num_actions: tabular_num_actions

policy: null
