name: dt_rmax_ucb

builder:
  _target_: rl_research.agents.dt_rmax_ucbpolicy_planner.DTRMaxNStepAgent

params:
  _target_: rl_research.agents.dt_rmax_ucbpolicy_planner.DTRMaxNStepParams
  num_states: null
  num_actions: null
  discount: 0.9
  learning_rate: 0.1
  initial_value: 0.0
  horizon: 5
  m: 100
  r_max: 1.0
  dynamics_model: null
  beta: 1.0
  use_time_bonus: true

autofill:
  num_states: tabular_num_states
  num_actions: tabular_num_actions
  dynamics_model: env_expectation

policy: null
