name: rmax_mcts

builder:
  _target_: rl_research.agents.rmax_mcts.RMaxMCTSAgent

params:
  _target_: rl_research.agents.rmax_mcts.RMaxMCTSAgentParams
  num_states: null
  num_actions: null
  discount: 0.9
  dynamics_model: null
  num_simulations: 16
  max_depth: 10
  exploration_constant: 100.0
  r_max: 6.0
  m: 30
  initial_value: null

autofill:
  num_states: tabular_num_states
  num_actions: tabular_num_actions
  dynamics_model: env_expectation

policy: null
