name: rmax_mcts_empirical_d50_n32_m16_b40

builder:
  _target_: rl_research.agents.rmax_mcts.RMaxMCTSAgent

params:
  _target_: rl_research.agents.rmax_mcts.RMaxMCTSAgentParams
  num_states: null
  num_actions: null
  discount: 0.9
  num_simulations: 32
  max_depth: 50
  exploration_constant: 40.0
  r_max: 6.0
  m: 16
  initial_value: null
  dynamics_model:
    _target_: rl_research.models.EmpiricalTabularModel
    num_states: null
    num_actions: null

autofill:
  num_states: tabular_num_states
  num_actions: tabular_num_actions

policy: null

