name: rmax

builder:
  _target_: rl_research.agents.RMaxAgent

params:
  _target_: rl_research.agents.RMaxParams
  num_states: null
  num_actions: null
  discount: 0.9
  threshold: 0.01
  r_max: 6.0
  m: 1

autofill:
  num_states: tabular_num_states
  num_actions: tabular_num_actions

policy: null
