name: dt_ucb

builder:
  _target_: rl_research.agents.DTUCBPlanner

params:
  _target_: rl_research.agents.DTUCBParams
  num_states: null
  num_actions: null
  discount: 0.9
  learning_rate: 0.05
  initial_value: 0.0
  horizon: 3
  beta: 20.0
  dynamics_model: null
  use_time_bonus: true

autofill:
  num_states: tabular_num_states
  num_actions: tabular_num_actions
  dynamics_model: env_expectation

policy: null
