name: qlearning_randomwalk

builder:
  _target_: rl_research.agents.QLearningAgent

params:
  _target_: rl_research.agents.QlearningParams
  num_states: null
  num_actions: null
  discount: 0.9
  initial_epsilon: 1.0
  learning_rate: 0.1
  initial_value: 0.0

autofill:
  num_states: tabular_num_states
  num_actions: tabular_num_actions

policy: null
